# Generated by Django 4.2.7 on 2023-11-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='starwarspeople',
            name='reference',
            field=models.IntegerField(default=1),
        ),
    ]
