# Generated by Django 4.2.7 on 2023-11-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapi', '0002_starwarspeople_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starwarspeople',
            name='films',
        ),
        migrations.RemoveField(
            model_name='starwarspeople',
            name='species',
        ),
        migrations.RemoveField(
            model_name='starwarspeople',
            name='starships',
        ),
        migrations.RemoveField(
            model_name='starwarspeople',
            name='vehicles',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.DeleteModel(
            name='Starship',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.AddField(
            model_name='starwarspeople',
            name='films',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='starwarspeople',
            name='species',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='starwarspeople',
            name='starships',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='starwarspeople',
            name='vehicles',
            field=models.JSONField(null=True),
        ),
    ]
