# Generated by Django 4.2.7 on 2023-11-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapi', '0003_remove_starwarspeople_films_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starwarspeople',
            name='reference',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
