# Generated by Django 4.2.7 on 2023-11-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapi', '0004_alter_starwarspeople_reference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='Ratings',
        ),
    ]
